dist: trusty
sudo: required
language:
        - cpp

compiler:
        - gcc

addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                       - clang
                       - cmake

script:
        - mkdir build
        - cd build && cmake ..
        - make
